export const PLAYER_POSITIONS = {
  goalkeeper: "Portero",
  leftWingBack: "Carrillero izquierdo",
  rightWingBack: "Carrillero derecho",
  leftBack: "Lateral izquierdo",
  rightBack: "Lateral derecho",
  centreBack: "Defensa central",
  centralDefensiveMidfielder: "Medio centro defensivo",
  centralMidfielder: "Medio centro",
  centralAttakingMidfielder: "Centro medio ofensivo",
  leftMidfielder: "Medio izquierdo",
  rightMidfielder: "Medio derecho",
  outsideLeft: "Externo izquierdo",
  outsideRight: "Externo derecho",
  centralStriker: "Delantero central",
  rightStriker: "Segundo delantero",
};
